### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mayn** [mayn/packer.py#2]
Add walkthrough docs covering all features

**Comment by gunjapapi** [comment]
Hi Mayn, 

Appreciate the work that you have done. I see that you've added support for multiple vars. I was wondering if you could let us know the syntax for it.

**Comment by mayn** [comment]
hi @gunjapapi ,
i released v0.3.0 which supports this feature.
The way to signal this is to pass in a dictionary as the value of the arg.

I've updated the docs and added an example here https://github.com/mayn/packer.py/tree/master#repeating-command-options

Let me know if this helps.

**Comment by mayn** [comment]
@gunjapapi , haven’t heard back. Closing out this issue as it was a task in  my v0.3.0 release. 
If you are still having issues please open a new ticket. Thanks

**Comment by gunjapapi** [comment]
Thanks for the update Matt,

Apologies, I have not had a chance to test it out. Will let you know how I go soon.

Cheers
gpapi
